version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
      timezone: 'US/Pacific'
    versioning-strategy: 'increase'
    open-pull-requests-limit: 10
