module.exports = {
    overrides: [
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'prettier',
            ],
            files: ['*.js'],
        },
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'staples/configs/react',
                'staples/configs/react-hooks',
                'staples/configs/react-native',
                'prettier',
            ],
            files: ['*.jsx'],
        },
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'staples/configs/rnx-kit',
                'staples/configs/typescript',
                'prettier',
            ],
            files: ['*.ts'],
        },
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'staples/configs/rnx-kit',
                'staples/configs/typescript',
                'staples/configs/react',
                'staples/configs/react-hooks',
                'staples/configs/react-native',
                'prettier',
            ],
            files: ['*.tsx'],
        },
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'staples/configs/react',
                'staples/configs/react-hooks',
                'staples/configs/react-native',
                'staples/configs/jest',
                'staples/configs/testing-library',
                'staples/configs/overrides/tests',
                'prettier',
            ],
            files: ['**/{__tests__,__mocks__,test}/**/*.js?(x)', '**/?(*.)+(spec|test).js?(x)', '**/jest-setup.js'],
        },
        {
            extends: [
                'staples',
                'staples/configs/import',
                'staples/configs/unicorn',
                'staples/configs/promise',
                'staples/configs/eslint-comments',
                'staples/configs/regexp',
                'staples/configs/rnx-kit',
                'staples/configs/typescript',
                'staples/configs/react',
                'staples/configs/react-hooks',
                'staples/configs/react-native',
                'staples/configs/jest',
                'staples/configs/testing-library',
                'staples/configs/overrides/tests',
                'staples/configs/overrides/typescript-tests',
                'prettier',
            ],
            files: ['**/{__tests__,__mocks__,test}/**/*.ts?(x)', '**/?(*.)+(spec|test).ts?(x)'],
        },
    ],
};
